"use strict";
var tools = require("./util/tools"),
    pentNum = tools.pentNum;
/*
 * Pentagon numbers
 * Problem 44
 * Pentagonal numbers are generated by the formula, P_n=n(3n−1)/2. The first 
 * ten pentagonal numbers are: 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * 
 * It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their 
 * difference, 70 − 22 = 48, is not pentagonal.
 * 
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum 
 * and difference are pentagonal and D = |Pk − Pj| is minimised; what 
 * is the value of D?
 * 
 * Answer: 5482660
 */

function init() {
	var o = "nothing yet";

	var i = 1;
	var running = true;
	while (running) {
		i += 1;
		for (var j=1; j<i; j++) {
			var a = pentNum(i);
			var b = pentNum(j);
			if (a != b && isPentagonalNumber(a+b) && isPentagonalNumber(Math.abs(a-b)) ) {
				// console.log(i,j,a,b,a+b,Math.abs(a-b));
				o = Math.abs(a-b);
				running = false;
				break;
			}
		}
	}

    return o;
}

function isPentagonalNumber(n) {
	var p = parseInt( (0.5 + Math.sqrt(0.25+(6*n))) / 3, 10);
	return tools.pentNum(p) == n;
}

module.exports.init = init;
